name: arc_app
description: "Arc App - Reproductor de música local con motor de audio personalizado."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.0
  arc_engine:
    git:
      url: https://github.com/FYSPA/Arc-Engine.git
      ref: main
  arx_canvas:
    git:
      url: https://github.com/FYSPA/Arx-Canvas.git
      ref: main
  palette_generator: ^0.3.3+4
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logos/
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
          weight: 900
    - family: Broken
      fonts:
        - asset: assets/fonts/broken.ttf
        - asset: assets/fonts/broken_filled.ttf
